
exceptions_arr = {
    'ValueError': 'Введены данные некорректного типа',
    'WrongLimitsArgument': 'Введенные данные не соответсвуют ни одному пункту',
    'TooMuchArguments': 'Передано слишком много аргументов',
    'NegativeStepException': 'Шаг должен быть положительным',
    'NegativeAccuracy': 'Отрицательная погрешность вычислений'
}
